version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - db:/app/db

  frontend:
    build: ./frontend
    ports:
      - "9080:9080"

volumes:
  db:
